# Generated by Django 2.0 on 2019-01-04 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('DOJ', models.DateField(default=datetime.date(2019, 1, 4))),
                ('address', models.TextField(max_length=100)),
                ('city', models.CharField(max_length=20)),
                ('DOB', models.DateField()),
                ('salary', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('DOJ',),
            },
        ),
    ]
