# Generated by Django 2.0 on 2019-01-04 17:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20190104_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='DOJ',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
