# Generated by Django 2.1.4 on 2019-01-03 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Medicine_Details',
            new_name='Medicine_Detail',
        ),
    ]
