# Generated by Django 2.0 on 2019-01-03 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_auto_20190103_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine_detail',
            old_name='type',
            new_name='medicine_type',
        ),
        migrations.RenameField(
            model_name='medicine_type',
            old_name='type',
            new_name='medicine_type',
        ),
    ]
